---
title: "cleaning variables"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

がん検診にかかる経費は、市町村の一般財源から措置されており、国が地方交付税で措置している。
地方交付税の算定に際しては、全国の標準的な財政需要を基礎として算定しているため、市町村の財政需要が全国平均を上回る場合、市町村の負担額が増えることとなる。
→富んだ市町村ほど地方交付税がもらえなくて検診予算のやりくりが出来なくなる。
→富める市町村が多い都道府県ほど、地方交付税がもらえない市町村が多くなる、すなわち検診受診を進めたくない市町村が多くなる。
地方交付税による補填は、国の算出方法が明らかに示されていないが、「国全体の5つのがん検診の平均受診率を想定し、それでかかる費用の2分の1を交付税として地方に与える」という形らしい。
つまり、平均を超えれば超えるほど負担が大きくなる、平均を下回るほどに得をする仕組みということだ。

そもそも地方交付税とは？
地方自治体の運営資金は税収入だが、その額はかなり偏在している。これを補うために国から出ている財源で、地方間の税収の不均衡を是正し均衡化するために配られている。
そのおおもとの財源は国税で、所得税・法人税の3割、酒税の半分、消費税の2割、地方法人税の全額がこれに充てられている。
地方交付税は使途が限定されない一般財源であり、使用目的を定めた増額や減額はできない。

地方交付税には普通交付税と特別交付税の2種類がある。
普通交付税が全体の9割以上を占める。一般的な財政需要に対する財源不足額に見合った額として算定され、交付される。
財源不足額の算定は法的に規定された計算方法で行われる。基準財政需要額に対して収入額が超過しているとされた地方公共団体に対しては地方交付税は交付されない。これを「不交付団体」という。これを判断する基準の一つとして「財政力指数」がある。


平成21年度、国は補正予算で特に検診受診率の低い。。。だそうだが、女性特有の眼について、時限措置の予定で、一定の年齢（CVCで20to40, bcで40to60, 5歳刻みで）を対象に無料で検診を受診できる補助事業を実施することとなった。
が、結局23年度以降は補助率50%で市町村事業になっている

